# Site settings
title:          mbe wiki
description:    "Uma documentação do aprendizado de 3 devinhas"
url:            "https://mbe-co.github.io/"

# Author
author:
  name:         Fernanda, Maria e Emily
  url:          https://mbe-co.github.io/
  # email:

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-remote-theme
  # - jemoji #Uncomment this to allow emoji in your post

remote_theme: chesterhow/tale

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus:         jekyll-tale